name: Deploy

on:
  workflow_call:

jobs:
  sub_deploy:
    runs-on: ubuntu-latest

    if: success()
    
    environment:
      name: github-pages 
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: frontend-build-${{ github.run_id }}
          merge-multiple: true

      - name: Debug files
        run: ls -R

      # Flatten nếu cần (rất hay cần)
      # - name: Prepare deploy folder
      #   run: |
      #     mkdir public
      #     find dist -type f -exec cp {} public/ \;

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show deployed URL
        run: echo "🚀 Site URL --- ${{ steps.deployment.outputs.page_url }}"