name: Full Workflow

on:
  push:
    branches: [main, master]
    tags: ['v*']
    paths: ['frontend/**', '.github/workflows/**']
  # pull_request:
  #   paths: ['frontend/**', '.github/workflows/**']

permissions: 
  contents: write
  pages: write
  id-token: write

concurrency: 
  group: frontend-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
# =============================== AUTO CREATE BETA TAG ===============================
  auto-tag:
    needs: build
    uses: ./.github/workflows/auto-tag.yml
# =============================== CREATE RELEASE ===============================
  release:
    needs: [build, auto-tag]
    uses: ./.github/workflows/release.yml
# =============================== CREATE DEPLOYMENT ===============================
  deploy:
    needs: release
    uses: ./.github/workflows/deploy.yml